### ISSUE TITLE
'Tiling' on heatmaps

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/CairoMakie.jl#11]
Heatmaps in CairoMakie 'tile', like this:

```julia
using AbstractPlotting, CairoMakie
AbstractPlotting.current_backend[] = CairoMakie.CairoBackend("./temp.svg")
heatmap(rand(10, 10))
```

yields this: (sorry for the weird border, it's a screenshot)

<img width="1268" alt="Screen Shot 2019-04-19 at 10 30 16  59900AM" src="https://user-images.githubusercontent.com/32143268/56428657-29f04100-628e-11e9-8910-2088f4d6b2a0.png">

and switching to PNG backend yields this:

![temp](https://user-images.githubusercontent.com/32143268/56428698-44c2b580-628e-11e9-9d07-ff65e50fb824.png)

This is the function that (I think) draws a heatmap in CairoMakie.

https://github.com/JuliaPlots/CairoMakie.jl/blob/cae15f292ff9293a2ee0befc4a4c71a39a508971/src/CairoMakie.jl#L239-L258

cc: @cormullion - would you mind taking a look?

**Comment by asinghvi17** [comment]
`heatmap(rand(500, 500))` looks like this:

<img width="1266" alt="Screen Shot 2019-04-19 at 10 33 57  38100AM" src="https://user-images.githubusercontent.com/32143268/56428807-b6026880-628e-11e9-94a7-b1cb3566c017.png">

so maybe it's only a problem at lower sizes?

**Comment by asinghvi17** [comment]
excuse me wtf png backend?

```julia
using AbstractPlotting, CairoMakie
AbstractPlotting.current_backend[] = CairoMakie.CairoBackend("./temp.png")
heatmap(rand(500, 500))
```
![temp](https://user-images.githubusercontent.com/32143268/56428973-4f317f00-628f-11e9-9527-f7d50ef7a218.png)

It's rendering pixel wise, and the rest are just based on column or row?

`heatmap(rand(200, 200))`
![temp](https://user-images.githubusercontent.com/32143268/56429046-80aa4a80-628f-11e9-9b4c-ef87c2e9ee9a.png)

**Comment by SimonDanisch** [comment]
i have no Idea :-D there aren't even that many parameters to mess up^^

**Comment by cormullion** [comment]
would love to help but I'm clueless in this realm... 😀😟

**Comment by asinghvi17** [comment]
I've been looking through some of the examples on Cairo.jl, and it seems like the main culprit might be `Cairo.pattern_set_extend`...just putting it here as a note so I can go back to it.

**Comment by SimonDanisch** [comment]
good point, maybe they interact unexpectatly with scaling or so

**Comment by asinghvi17** [comment]
https://github.com/JuliaPlots/CairoMakie.jl/blob/cae15f292ff9293a2ee0befc4a4c71a39a508971/src/CairoMakie.jl#L251

does this convert to some unit?  If so, that would explain the tiling - the pattern is not large enough to scale with the image, so it repeats.  If Cairo is set to some render size (maybe 800*800px) that would explain the magic number as well.  I will look at Cairo's docs some later time - I have a bunch of other things I have to finish as well, but hopefully I will have some idea by end of week.

**Comment by asinghvi17** [comment]
🤣 

```julia
using AbstractPlotting, CairoMakie
showlibrary(:colorcet)
```
![Screen Shot 2019-05-08 at 10 36 20 AM](https://user-images.githubusercontent.com/32143268/57383720-4856a780-717d-11e9-8def-5a66dddf50e2.png)

**Comment by asinghvi17** [comment]
So I think this means `text` is broken as well...

**Comment by asinghvi17** [comment]
If I comment this out then it doesn't plot any heatmap:

https://github.com/JuliaPlots/CairoMakie.jl/blob/cae15f292ff9293a2ee0befc4a4c71a39a508971/src/CairoMakie.jl#L252

**Comment by asinghvi17** [comment]
Could it be that Cairo is interpreting our image as pixel data?  @SimonDanisch

**Comment by asinghvi17** [comment]
A large tiled heatmap on CairoMakie no longer fails when saving to PNG.  
![iTerm2 oPxxNp](https://user-images.githubusercontent.com/32143268/61105681-47513780-a498-11e9-9a41-a0c09cf9bd49.png)

Sidenote: I love that this integrates into the terminal with TerminalExtensions.jl.  

![Uploading Screen Shot 2019-07-12 at 11.30.04 .32200AM.png…]()

**Comment by asinghvi17** [comment]
The saving for svg appears broken here:

[heatmap.svg.txt](https://github.com/JuliaPlots/CairoMakie.jl/files/3385168/heatmap.svg.txt)
(just remove the .txt)

and JPEG
![heatmap](https://user-images.githubusercontent.com/32143268/61106205-f6dad980-a499-11e9-818c-72619f253bf5.jpeg)
and PNG
![heatmap](https://user-images.githubusercontent.com/32143268/61106209-fcd0ba80-a499-11e9-88ff-8172b92dc604.png)
seem to work fine.

**Comment by asinghvi17** [comment]
But we have a problem with small heatmaps:
![heatmap](https://user-images.githubusercontent.com/32143268/61106843-f9d6c980-a49b-11e9-9e74-0d386110eda8.png)
