### ISSUE TITLE
Text is broken

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/CairoMakie.jl#16]
Images are fine, it's just text now...
![iTerm2 CZG5pd](https://user-images.githubusercontent.com/32143268/61683918-0b8a5d80-ad35-11e9-8be0-e26e486b6adc.png)

**Comment by asinghvi17** [comment]
It seems the `fontsize` attribute is not respected, for one...

**Comment by SimonDanisch** [comment]
This should be somewhat fixed now - although text still looks bad :D

**Comment by asinghvi17** [comment]
This was a screenshot taken at the time of posting...
