### ISSUE TITLE
Heatmap offset

### ISSUE THREAD

**Issue by grero** [JuliaPlots/CairoMakie.jl#25]
I came across this issue while trying to use this package to save some heat maps as PDFs. Basically, CairoMakie seems to be shifting the heat maps slightly compared to using GLMakie + FileIO to save the same plot

```julia
using MakieLayout, CairoMakie, AbstractPlotting, GLMakie, FileIO
AbstractPlotting.inline!(false)
scene = Scene(resolution=(800,600), camera=campixel!);
layout = GridLayout(scene, alignmode=Outside(20));
la = layout[1,1] = LAxis(scene)
heatmap!(la, rand(100,100))
la.title = "GL"
AbstractPlotting.current_backend[] = GLMakie.GLBackend()
display(scene)
FileIO.save("imgtestgl.png",scene)
tmp = "imgtestcairo.png"
AbstractPlotting.current_backend[] = CairoMakie.CairoBackend(tmp)
la.title = "Cairo"
scene
```
![imgtestgl](https://user-images.githubusercontent.com/1245900/74632523-849e4600-519a-11ea-9260-17fa43d63182.png)
![imgtestcairo](https://user-images.githubusercontent.com/1245900/74632545-8e27ae00-519a-11ea-840e-ea128f9cab8d.png)

**Comment by asinghvi17** [comment]
That was an off-by-one error, should be fixed at some point.  The fix is on one of these 20 branches :D

**Comment by jkrumbiegel** [comment]
nah this is not the off by one, but the y flip. also fixed
