### ISSUE TITLE
Axis clipping doesn't work correctly, layout is wrong

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/CairoMakie.jl#27]
With MakieLayout:
![nullclines](https://user-images.githubusercontent.com/32143268/75085524-42596980-54f8-11ea-83a9-9e1141cbaf9d.png)

**Comment by asinghvi17** [comment]
For clipping, it looks like this could work:
https://github.com/JuliaGraphics/Cairo.jl/blob/master/samples/sample_clip_image.jl

**Comment by SimonDanisch** [comment]
I must admit, layouting almost works by accidant :D I've never did anything special, but it's almost working out, by just applying the projections :D
