### ISSUE TITLE
Bboxes or ticks are off

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/CairoMakie.jl#32]
Consider the test image 
![test_image](https://user-images.githubusercontent.com/32143268/76420170-fa648e80-63a1-11ea-94a5-f6c0f62781ca.jpg)
and the reference image 
![ref_image](https://user-images.githubusercontent.com/32143268/76420178-fe90ac00-63a1-11ea-9fbc-21619ae5312f.jpg)

or
test
![test_image](https://user-images.githubusercontent.com/32143268/76420192-04868d00-63a2-11ea-8688-59d737be2703.jpg)
reference
![ref_image](https://user-images.githubusercontent.com/32143268/76420203-094b4100-63a2-11ea-9f36-ad7b001d31f2.jpg)

or

test
![test_image](https://user-images.githubusercontent.com/32143268/76420263-241db580-63a2-11ea-9b0b-b141580d8088.jpg)
ref
![ref_image](https://user-images.githubusercontent.com/32143268/76420266-25e77900-63a2-11ea-9165-9458250ee6fb.jpg)

**Comment by SimonDanisch** [comment]
That's weird...axes & boundingboxes should be 100% backend independent...
Can you try this in Makie? Maybe this is a regression?

**Comment by asinghvi17** [comment]
Oh, that was stupid...this is with the experimental perf optimizations of @jkrumbiegel's PR to PlotUtils.  NVM, will revert to the original for now.
code:
```julia
coordinates = [
           0.0 0.0;
           0.5 0.0;
           1.0 0.0;
           0.0 0.5;
           0.5 0.5;
           1.0 0.5;
           0.0 1.0;
           0.5 1.0;
           1.0 1.0;
       ]
       connectivity = [
           1 2 5;
           1 4 5;
           2 3 6;
           2 5 6;
           4 5 8;
           4 7 8;
           5 6 9;
           5 8 9;
       ]
       color = [0.0, 0.0, 0.0, 0.0, -0.375, 0.0, 0.0, 0.0, 0.0]
       scene = mesh(coordinates, connectivity, color = color, shading = false)
       wireframe!(scene[end][1], color = (:black, 0.6), linewidth = 3)
```
