### ISSUE TITLE
Interpolation doesn't work with heatmaps

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/CairoMakie.jl#33]
GLMakie:
![ref_image](https://user-images.githubusercontent.com/32143268/76420349-44e60b00-63a2-11ea-8b0b-9a734aad1bf2.jpg)
CairoMakie:
![test_image](https://user-images.githubusercontent.com/32143268/76420355-47486500-63a2-11ea-88f1-aa9d17c84a49.jpg)

or

GLMakie:
![ref_image](https://user-images.githubusercontent.com/32143268/76420626-b58d2780-63a2-11ea-9403-b8589819b21e.jpg)

CairoMakie:
![test_image](https://user-images.githubusercontent.com/32143268/76420684-ca69bb00-63a2-11ea-94d4-59db8157aeb2.jpg)

**Comment by asinghvi17** [comment]
Cairo has some filters:
`CAIRO_FILTER_BEST     CAIRO_FILTER_BILINEAR  CAIRO_FILTER_FAST      CAIRO_FILTER_GAUSSIAN  CAIRO_FILTER_GOOD      CAIRO_FILTER_NEAREST`

which we can apply to surfaces like so:
```julia
Cairo.pattern_set_filter(pattern, Cairo.FILTER_BILINEAR) # or whatever
```

**Comment by asinghvi17** [comment]
https://github.com/JuliaPlots/CairoMakie.jl/blob/742d667f8dd26db1556afe44b0b0bb6ddaf6a54e/src/CairoMakie.jl#L295

Looks like this has no effect.

**Comment by asinghvi17** [comment]
It seems that `FILTER_BEST` is fake and doesn't do anything.

**Comment by SimonDanisch** [comment]
Yeah, if I remember correctly, this is an svg backend problem...

**Comment by jkrumbiegel** [comment]
interpolation is handled by whatever displays svgs or pdfs, so I'll close this
