### ISSUE TITLE
Allow using pandoc markdown / passing raw text to cairo

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/CairoMakie.jl#37]
would help the italics situation, which I need to plot stuff for papers

**Comment by SimonDanisch** [comment]
What is exactly the italic situation?

**Comment by asinghvi17** [comment]
Cairo doesn't like italic unicode characters (though the font supports it)

**Comment by asinghvi17** [comment]
To paraphrase from another discussion, the font doesn't support it, and vector-of-font support exists.  This would be better implemented by a rich text type in AbstractPlotting.
