### ISSUE TITLE
y label is jumbled

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/CairoMakie.jl#42]
![a](https://user-images.githubusercontent.com/3281957/77540076-c52c6600-6ea2-11ea-9947-884bed9d7428.png)
This weird y-label results from this MWE:
```julia
using CairoMakie, Makie, MakieLayout, FileIO
CairoMakie.activate!()
scene, layout = layoutscene();
ax = layout[1, 1] = LAxis(scene, xlabel = "X (cm)", ylabel = "Y (cm)")
lines!(ax, Tuple.(eachrow(rand(10,2))))
FileIO.save("a.png", scene)
```

**Comment by asinghvi17** [comment]
Looks like a text layouting bug.  I suspect it might actually be that the glyphs are rotated incorrectly; the text rotations example in MakieGallery has a lot of issues here.  We would have to fix the conversion of the quaternion rotation from AbstractPlotting into a simple angle here...
