### ISSUE TITLE
Wrong marker position

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/CairoMakie.jl#46]
This is using PR #44.
The position of a marker should be anchored on its center, not its edges.
In the following MWE you'll notice that the red marker's location is not centered on `(0, 0)`:
```julia
scene = scatter(Tuple.(eachrow(rand(3,2))));
scatter!([0], [0], color = :red);
```
![a](https://user-images.githubusercontent.com/3281957/77622940-7b458d80-6f3f-11ea-9844-f9a1da16904e.png)
(not to mention the glyphs and y-label)

**Comment by asinghvi17** [comment]
Is this on master?

**Comment by yakir12** [comment]
this is on as/marker
